### ISSUE TITLE
Publish PRNG standalone?

### ISSUE THREAD

**Issue by ocramz** [jez/bingo-sim#1]
It would be great to have the Haskell implementation of xoshiro as a standalone package, if only for benchmarking.

There is at least one already available implementation of XORshift (which I understand is the "predecessor" of xoshiro) : 

https://hackage.haskell.org/package/xorshift-plus
https://github.com/syocy/xorshift-plus

**Comment by jez** [comment]
Thanks for the interest. I have absolutely zero interest in maintaining public library packages. 😅 Feel free to take the code and use it in accordance with the license.
